name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gover: ["1.17", "1.18", "1.19"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "${{ matrix.gover }}"

    - name: Setup Golang caches
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.gover }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Setup the project
      run: go mod download

    - name: Verify go fmt
      run: test -z "$(go fmt ./...)"

    - name: Verify go vet
      run: test -z "$(go vet ./...)"

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
